import "./globals.css";

import { Plus_Jakarta_Sans } from "next/font/google";

import GlobalProvider from "@/components/shared/GlobalProvider";
import RootNavbar from "@/components/shared/RootNavbar";
import RootFooter from "@/components/shared/RootFooter";

const PlusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Talent Pro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={PlusJakartaSans.className}>
        <main className="bg-base min-h-screen">
          <GlobalProvider>{children}</GlobalProvider>
        </main>
      </body>
    </html>
  );
}
